<?php
class SuperUser extends User implements ISuperUser {
    public $role;

    function __construct($name, $login, $password, $role)
    {
        parent::__construct($name, $login, $password);
        $this->role = $role;
    }
    function showinfo()
    {
        parent::showinfo(); // TODO: Change the autogenerated stub
        echo "<p>Role :{$this->role}";
    }
    function getInfo()
    {
        $rc = new ReflectionClass($this);
        $attributes = $rc->getProperties();

        $result = [];
        foreach ($attributes as $attribute) {
            $name = $attribute->getName();
            $result[$name] = $this->{$name};
        }

        return $result;


    }

}