<?php
interface  ISuperUser{
    function getInfo();

}

abstract class UserAbstract{
    abstract function showinfo();
}

class User extends UserAbstract {
    public $name;
    public $login;
    public $password;

    function __construct($name, $login, $password){
        $this->name = $name;
        $this->login = $login;
        $this->password = $password;
    }
    function __destruct(){
        echo  "<p>Пользователь {$this->login}  удалён";
    }
   function showinfo(){
       echo $this->drawLine();
       echo "<p>Name :{$this->name}";
       echo "<p>Login :{$this->login}";
       echo "<p>Paswword :{$this->password}";

}
    function drawLine(){
       echo "<hr>";
    }
};
class SuperUser extends User implements ISuperUser {
    public $role;

    function __construct($name, $login, $password, $role)
    {
        parent::__construct($name, $login, $password);
        $this->role = $role;
    }
    function showinfo()
    {
        parent::showinfo(); // TODO: Change the autogenerated stub
        echo "<p>Role :{$this->role}";
    }
    function getInfo()
    {
        $rc = new ReflectionClass($this);
        $attributes = $rc->getProperties();

        $result = [];
        foreach ($attributes as $attribute) {
            $name = $attribute->getName();
            $result[$name] = $this->{$name};
        }

        return $result;


    }

}
$user1 = new User("Konstantin","wusnoop", "qwerty" );
$user2 = new User("Misha","Anduin","asdfgh"  );
$user3 = new User("Sylvana", "Death", "For the Horde");

$user = new SuperUser("Kevin", "Smith", "WTF", "Admin");

$user1->showinfo();
$user2->showinfo();
$user3->showinfo();
$user->showinfo();
echo "<hr>";
print_r($user->getInfo());

